
-- Table for storing assigned staff roles
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS staff_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    duty TEXT NOT NULL CHECK (duty IN ('Registration', 'Room Allocation')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
