
-- Table for storing room allocations
CREATE TABLE IF NOT EXISTS room_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block TEXT NOT NULL CHECK (block IN ('N Block', 'P Block')),
    room_name TEXT NOT NULL,
    capacity INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
