-- SQL to create the volunteer_assignments table
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS volunteer_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone_no TEXT NOT NULL,
    room_no TEXT NOT NULL,
    time_slot TEXT NOT NULL,
    is_present BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
